#!/bin/bash
echo "============================================================"
echo "           HVF EXECUTIVE SYSTEM HEALTH DASHBOARD            "
echo "============================================================"
echo "[LIVE CRON JOB SCHEDULER]"
crontab -l | grep -v "^#"
echo "------------------------------------------------------------"
echo "[OMNI SIGHT CORE TELEMETRY]"
tail -n 3 /home/mrshumphrey3251/HVF_NEXUS_CORE_V2_PRIVATE/omni_sight_execution.log 2>/dev/null || echo "Log pending execution."
echo "------------------------------------------------------------"
echo "[INTELLIGENCE SCRAPER TELEMETRY]"
tail -n 3 /home/mrshumphrey3251/HVF_INTEL_SCRAPER/scraper_cron.log 2>/dev/null || echo "Log pending execution."
echo "------------------------------------------------------------"
echo "[COMMERCIAL AUTORESPONDER TELEMETRY]"
tail -n 3 /home/mrshumphrey3251/HVF_MEDIA_MATRIX/autoresponder_cron.log 2>/dev/null || echo "Log pending execution."
echo "------------------------------------------------------------"
echo "[OSINT AGGREGATOR TELEMETRY (LATEST TARGET)]"
tail -n 3 /home/mrshumphrey3251/HVF_INTEL_SCRAPER/osint_targets.log 2>/dev/null || echo "Log pending execution."
echo "============================================================"
echo "ALL BACKGROUND ENGINES VERIFIED. SYSTEM SECURE."
